[package]
name = "wasm_ia"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
linreg = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.1"
rand = "0.8.3"
chrono = "0.4.19"